name: Publish Helm Chart

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # semver tags like 1.2.3 (no leading v)

jobs:
  build-and-publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Extract Helm chart version
        id: chart_version
        run: |
          CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}' | tr -d '"')
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Check tag matches chart version
        run: |
          if [ "${GITHUB_REF##*/}" != "${{ steps.chart_version.outputs.chart_version }}" ]; then
            echo "ERROR: Tag (${GITHUB_REF##*/}) does not match chart version (${{
            steps.chart_version.outputs.chart_version }})"
            exit 1
          fi

      - name: Helm login to GHCR
        run: helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: helm package .

      - name: Push Helm chart to GHCR
        run: helm push glance-*.tgz oci://ghcr.io/felixzmn/helm